// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: service/user/rpc/user.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserReq) Reset() {
	*x = FindUserReq{}
	mi := &file_service_user_rpc_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserReq) ProtoMessage() {}

func (x *FindUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_rpc_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserReq.ProtoReflect.Descriptor instead.
func (*FindUserReq) Descriptor() ([]byte, []int) {
	return file_service_user_rpc_user_proto_rawDescGZIP(), []int{0}
}

func (x *FindUserReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FindUserReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type FindUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	RealName      string                 `protobuf:"bytes,4,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	RoleLevel     int32                  `protobuf:"varint,5,opt,name=role_level,json=roleLevel,proto3" json:"role_level,omitempty"`
	DepartmentId  int64                  `protobuf:"varint,6,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserResp) Reset() {
	*x = FindUserResp{}
	mi := &file_service_user_rpc_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserResp) ProtoMessage() {}

func (x *FindUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_rpc_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserResp.ProtoReflect.Descriptor instead.
func (*FindUserResp) Descriptor() ([]byte, []int) {
	return file_service_user_rpc_user_proto_rawDescGZIP(), []int{1}
}

func (x *FindUserResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FindUserResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *FindUserResp) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *FindUserResp) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *FindUserResp) GetRoleLevel() int32 {
	if x != nil {
		return x.RoleLevel
	}
	return 0
}

func (x *FindUserResp) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *FindUserResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetDeptSubtreeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeptId        int64                  `protobuf:"varint,1,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeptSubtreeReq) Reset() {
	*x = GetDeptSubtreeReq{}
	mi := &file_service_user_rpc_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeptSubtreeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeptSubtreeReq) ProtoMessage() {}

func (x *GetDeptSubtreeReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_rpc_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeptSubtreeReq.ProtoReflect.Descriptor instead.
func (*GetDeptSubtreeReq) Descriptor() ([]byte, []int) {
	return file_service_user_rpc_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetDeptSubtreeReq) GetDeptId() int64 {
	if x != nil {
		return x.DeptId
	}
	return 0
}

type GetDeptSubtreeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeptIds       []int64                `protobuf:"varint,1,rep,packed,name=dept_ids,json=deptIds,proto3" json:"dept_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeptSubtreeResp) Reset() {
	*x = GetDeptSubtreeResp{}
	mi := &file_service_user_rpc_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeptSubtreeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeptSubtreeResp) ProtoMessage() {}

func (x *GetDeptSubtreeResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_rpc_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeptSubtreeResp.ProtoReflect.Descriptor instead.
func (*GetDeptSubtreeResp) Descriptor() ([]byte, []int) {
	return file_service_user_rpc_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetDeptSubtreeResp) GetDeptIds() []int64 {
	if x != nil {
		return x.DeptIds
	}
	return nil
}

type ValidateTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenReq) Reset() {
	*x = ValidateTokenReq{}
	mi := &file_service_user_rpc_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenReq) ProtoMessage() {}

func (x *ValidateTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_rpc_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenReq.ProtoReflect.Descriptor instead.
func (*ValidateTokenReq) Descriptor() ([]byte, []int) {
	return file_service_user_rpc_user_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleLevel     int32                  `protobuf:"varint,3,opt,name=role_level,json=roleLevel,proto3" json:"role_level,omitempty"`
	DeptId        int64                  `protobuf:"varint,4,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResp) Reset() {
	*x = ValidateTokenResp{}
	mi := &file_service_user_rpc_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResp) ProtoMessage() {}

func (x *ValidateTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_rpc_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResp.ProtoReflect.Descriptor instead.
func (*ValidateTokenResp) Descriptor() ([]byte, []int) {
	return file_service_user_rpc_user_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateTokenResp) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ValidateTokenResp) GetRoleLevel() int32 {
	if x != nil {
		return x.RoleLevel
	}
	return 0
}

func (x *ValidateTokenResp) GetDeptId() int64 {
	if x != nil {
		return x.DeptId
	}
	return 0
}

var File_service_user_rpc_user_proto protoreflect.FileDescriptor

const file_service_user_rpc_user_proto_rawDesc = "" +
	"\n" +
	"\x1bservice/user/rpc/user.proto\x12\x04user\"B\n" +
	"\vFindUserReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\xd8\x01\n" +
	"\fFindUserResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12#\n" +
	"\rpassword_hash\x18\x03 \x01(\tR\fpasswordHash\x12\x1b\n" +
	"\treal_name\x18\x04 \x01(\tR\brealName\x12\x1d\n" +
	"\n" +
	"role_level\x18\x05 \x01(\x05R\troleLevel\x12#\n" +
	"\rdepartment_id\x18\x06 \x01(\x03R\fdepartmentId\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\",\n" +
	"\x11GetDeptSubtreeReq\x12\x17\n" +
	"\adept_id\x18\x01 \x01(\x03R\x06deptId\"/\n" +
	"\x12GetDeptSubtreeResp\x12\x19\n" +
	"\bdept_ids\x18\x01 \x03(\x03R\adeptIds\"(\n" +
	"\x10ValidateTokenReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"z\n" +
	"\x11ValidateTokenResp\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"role_level\x18\x03 \x01(\x05R\troleLevel\x12\x17\n" +
	"\adept_id\x18\x04 \x01(\x03R\x06deptId2\xc0\x01\n" +
	"\x04User\x121\n" +
	"\bFindUser\x12\x11.user.FindUserReq\x1a\x12.user.FindUserResp\x12C\n" +
	"\x0eGetDeptSubtree\x12\x17.user.GetDeptSubtreeReq\x1a\x18.user.GetDeptSubtreeResp\x12@\n" +
	"\rValidateToken\x12\x16.user.ValidateTokenReq\x1a\x17.user.ValidateTokenRespBBZ@github.com/sisyphus550/assets-db/backend/service/user/rpc/userpbb\x06proto3"

var (
	file_service_user_rpc_user_proto_rawDescOnce sync.Once
	file_service_user_rpc_user_proto_rawDescData []byte
)

func file_service_user_rpc_user_proto_rawDescGZIP() []byte {
	file_service_user_rpc_user_proto_rawDescOnce.Do(func() {
		file_service_user_rpc_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_user_rpc_user_proto_rawDesc), len(file_service_user_rpc_user_proto_rawDesc)))
	})
	return file_service_user_rpc_user_proto_rawDescData
}

var file_service_user_rpc_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_service_user_rpc_user_proto_goTypes = []any{
	(*FindUserReq)(nil),        // 0: user.FindUserReq
	(*FindUserResp)(nil),       // 1: user.FindUserResp
	(*GetDeptSubtreeReq)(nil),  // 2: user.GetDeptSubtreeReq
	(*GetDeptSubtreeResp)(nil), // 3: user.GetDeptSubtreeResp
	(*ValidateTokenReq)(nil),   // 4: user.ValidateTokenReq
	(*ValidateTokenResp)(nil),  // 5: user.ValidateTokenResp
}
var file_service_user_rpc_user_proto_depIdxs = []int32{
	0, // 0: user.User.FindUser:input_type -> user.FindUserReq
	2, // 1: user.User.GetDeptSubtree:input_type -> user.GetDeptSubtreeReq
	4, // 2: user.User.ValidateToken:input_type -> user.ValidateTokenReq
	1, // 3: user.User.FindUser:output_type -> user.FindUserResp
	3, // 4: user.User.GetDeptSubtree:output_type -> user.GetDeptSubtreeResp
	5, // 5: user.User.ValidateToken:output_type -> user.ValidateTokenResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_user_rpc_user_proto_init() }
func file_service_user_rpc_user_proto_init() {
	if File_service_user_rpc_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_user_rpc_user_proto_rawDesc), len(file_service_user_rpc_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_user_rpc_user_proto_goTypes,
		DependencyIndexes: file_service_user_rpc_user_proto_depIdxs,
		MessageInfos:      file_service_user_rpc_user_proto_msgTypes,
	}.Build()
	File_service_user_rpc_user_proto = out.File
	file_service_user_rpc_user_proto_goTypes = nil
	file_service_user_rpc_user_proto_depIdxs = nil
}
